### ISSUE TITLE
后端代码找寻合适的云服务商进行部署

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-backend#3]
cloud flare 提供了巨额免费的流量和解决方案（包括安全， dns，CDN 自动化部署等），可以试试把后端代码部署到这里。
cloud flare 官网：https://dash.cloudflare.com/4000d8bc4c9c3f9415aead72af9139dc
cloudns 官网：https://www.cloudns.net/main/
可以查看这个人的视频详细了解：https://www.youtube.com/@Tech_Shrimp

**Comment by funnyJackPeng** [comment]
经过调查，cloudflare 的 workers 和 pages 都是只支持部署静态资源网站，不能部署 spring boot 应用

**Comment by funnyJackPeng** [comment]
可以试试 aws 的 Amazon API Gateway

**Comment by funnyJackPeng** [comment]
经过研究， Elastic Beanstalk 可以提供一个docker image 然后直接运行；codebuild 和 codedeploy 可以执行绑定 github 仓库并执行 CI/CD 等操作。可以看看如何结合两者使用

**Comment by funnyJackPeng** [comment]
Elastic Beanstalk 只需要提供源码的 zip 文件就行，配置中可以配置是否使用数据库，然后自动创建一个随机名字的数据库。
spring boot 的 application 中配置好数据库的连接信息应该就能用了

**Comment by funnyJackPeng** [comment]
经过 BMS2 中的实践，spring boot 微服务项目在云端的运行方式是将每个需要的服务都打包成 docker image，然后再在云端使用每个 image。使用 gradle 的 bootBuildImage 命令可以快速打包成 docker image。具体可以参考 bms2 的 build-images.sh 文件所写的内容。

**Comment by funnyJackPeng** [comment]
打包成 docker image 后，不能在 docker 环境中获取到 aws secret manager 中的内容，所以还是暂时先把云端数据库帐号密码直接写道 application 中，之后再考虑安全性的问题。

打包成 docker image 后，直接使用 docker run 即可运行。在 aws 的 code build 和 deploy 中，写好打包命令就能 build 和 deploy 了。

**Comment by funnyJackPeng** [comment]
> 经过 BMS2 中的实践，spring boot 微服务项目在云端的运行方式是将每个需要的服务都打包成 docker image，然后再在云端使用每个 image。使用 gradle 的 bootBuildImage 命令可以快速打包成 docker image。具体可以参考 bms2 的 build-images.sh 文件所写的内容。

根据这里的 docker 实例，在 build 之前会先登录 aws 账号，之后可以试试登录过后是否就可以获取到 secret manager 中的信息了，记得给 build 的服务账号添加权限。

**Comment by funnyJackPeng** [comment]
目前 aws 存在三个问题：
1、code pipeline 不能识别到 imagedefine .json 文件，从而不能自动部署。
2、ecs 中部署的 service 不能通过公网 IP 直接访问。
3、没有域名以及路由分配，不能分配流量到对应的 service

**Comment by funnyJackPeng** [comment]
经过研究，部署一个服务到服务器上大概步骤如下：
1、创建云端数据库，并拿到数据库的 URL 和端口，密码可以由服务商的 secret manager 或者自己设置。将数据库设置为 public，公网直接可以访问，设置好后可以去 IDEA 或者其他工具中尝试连接。
2、创建 container registry，然后想办法通过命令行将build 好的 docker image 推送到此 registry 中
3、创建 container service，此为运行 docker 的服务，需要配置使用 registry 中的 image
4、创建 load balancer 和 api gateway，负责将公网的流量导入到 service 中，并同时实现负载均衡。

目前在试用 aws 中，每月成本已经达到 101 美元，并且网络时好时坏。不如去研究一下国内的云服务商如何操作。

**Comment by funnyJackPeng** [comment]
腾讯云没有 API 网关了，阿里云目前功能齐全，可以尝试使用

**Comment by funnyJackPeng** [comment]
![image](https://github.com/user-attachments/assets/57f64c8a-ce21-46c2-afe7-f2d626dacb1c)
目前阿里云已经成功通过外网访问到实例中的内容。
除了上面列出的步骤外，对于网络层面的配置，大致如下：
1、创建或使用已有的 VPC，确保阿里云的 ECI 使用了这个 VPC
2、创建 VPC 网关，连接 VPC 和公网，确保创建时选择的 VPC 是 ECI 中使用的 VPC。
3、创建弹性公网 IP （EIP），绑定到 VPC 上。
4、创建负载均衡器，转发流量。
具体点的内容可以参考 AI 的回答：
```
阿里云中如何配置公网 NET 网关和 VPC NET 网关，能从公网直接访问到 ECI 中的实例？
```
```
阿里云中 ECI 实例本身没有公网 IP，因此无法直接从公网访问。要实现从公网访问 ECI 实例，你需要结合使用以下服务：

虚拟私有云 (VPC): 确保你的 ECI 实例位于 VPC 网络中。
专有网络网关 (VPC 网关): 创建一个 VPC 网关，用于连接你的 VPC 网络和公网。
弹性公网 IP (EIP): 申请一个 EIP，并将其绑定到 VPC 网关上。
负载均衡器 (SLB): 创建一个 SLB 实例，并将其配置为将来自 EIP 的流量转发到你的 ECI 实例。
配置步骤:

创建 VPC 网关: 在 VPC 控制台，创建一个 VPC 网关，将其类型设置为 “公网网关”。
绑定 EIP: 在 EIP 控制台，申请一个 EIP，并将其绑定到 VPC 网关上。
创建 SLB 实例: 在 SLB 控制台，创建一个 SLB 实例，并选择 “公网” 类型。
配置监听器: 为 SLB 实例配置监听器，监听来自 EIP 的流量，并将其转发到后端服务器组。
创建后端服务器组: 创建一个后端服务器组，并将你的 ECI 实例添加到该组中。
配置健康检查: 为后端服务器组配置健康检查，确保 SLB 只将流量转发到健康的 ECI 实例。
说明:

SLB 实例可以通过多种方式将流量转发到 ECI 实例，例如轮询、加权轮询、最小连接数等。
你需要在安全组中配置相应的规则，允许来自 SLB 实例的流量访问你的 ECI 实例。
你可以使用阿里云提供的 Terraform 或 CloudFormation 等工具来自动化配置这些服务。
总结:

通过配置 VPC 网关、EIP 和 SLB，你可以将来自公网的流量转发到你的 ECI 实例，从而实现从公网访问 ECI 实例的目的。
```

**Comment by funnyJackPeng** [comment]
![image](https://github.com/user-attachments/assets/b33106b1-e8f5-4328-aff8-647d895c7a33)

最终达到的效果是使用a阿里云提供的 DNS 名称，拼接上自己的 URL path，然后能顺利访问自己实例中的内容

**Comment by funnyJackPeng** [comment]
目前距离自动化部署还差以下内容：
1、monolith service 在执行 build image 命令的时候存在问题
2、如何在 ECI 中创建多个组，然后使用同一个 DNS 名称，将不同 path 的流量导入到不同的 ECI 组中
3、使用阿里云的 CI\CD 产品，让每次代码提交到仓库后都可以执行 CI\CD 流程

**Comment by funnyJackPeng** [comment]
ECI 只能在创建的时候决定有几个容器，例如我们现在需要三个容器 email，monolith，migration。那就只能创建的时候开出三个容器，创建好容器组后就不能修改了，如果后面增加了需求，需要再加一个服务，则只能重新创建容器组。

这个问题暂时先不处理，先使用 ECI 跑通流程，之后如果有需求再看看有没有其他的产品可以用。

**Comment by funnyJackPeng** [comment]
经过调查
1、是因为 docker 版本过低，使用 docker desktop 升级到最新版后没有问题
2、上面已经回答
3、阿里云的云效 flow 有点过度包装了，想执行自定义命令的环境没有docker，使用带 docker 的环境则必须用 docker file。
结合目前项目后端也就两个命令的事儿，每次先手动发版，自动发版之后再研究。

**Comment by funnyJackPeng** [comment]
记录一下负载均衡的配置和使用：
![image](https://github.com/user-attachments/assets/dfb9b852-eaae-4445-9eea-90e3c2fda18d)
1、这里监听协议和端口选择 HTTP:80， 
![image](https://github.com/user-attachments/assets/06c70ad6-c6eb-4092-90b5-b7bba323ff9e)
2、服务器组这边选择好 ECI 容器后，监听端口要填 8080，与 spring 中的 port 设置保持一致，没有什么第一个 80 已经被上一步用了的说法

![image](https://github.com/user-attachments/assets/a3b49425-d3aa-4675-8ab0-e283b9d0a31b)

3、负载均衡提供的 DNS 解析域名已经包含了端口信息了，不需要再在后面加 `:8080` ,直接拼接 URL path 就行

**Comment by funnyJackPeng** [comment]
![image](https://github.com/user-attachments/assets/b9236352-914b-4fbc-8994-8dcf2f4c2308)
在 ECI 中，可以同时存在多个 service 并且使用同一个 port，流量会自动分发到对应的 container。

至此，已经成功使用阿里云部署了 spring boot 的微服务应用

**Comment by funnyJackPeng** [comment]
对于上面内容的更正：
同一个 ECI 容器组中的多个容器不能同时使用同一个 port，流量也不会自动分发。要实现类似 GAE 的 dispatch 自动分发的功能，需要做以下步骤：

1、将不同的 service 创建出不同的 ECI 容器组，这样不同的 ECI 都能使用 8080 端口了，如果是 job 这种不占用端口的一次性作业，则可以合在一个 ECI 容器组中（例如 monolith 和 migration ）
![image](https://github.com/user-attachments/assets/a4b30370-11c3-4c1b-b6ed-f172353b90bc)

2、负载均衡的服务器组中也创建多个 group，一个 group 对应一个 ECI 容器组，监听端口都为 8080
![image](https://github.com/user-attachments/assets/863c774f-b069-4804-9cc5-fb1df480fd07)

3、在负载均衡实例的监听规则中，转发规则就类似 dispatch 中的配置，什么路径转发到什么 service group 中去
![image](https://github.com/user-attachments/assets/e48a70e1-e19e-4ba5-ba39-39a08e3799cc)

**Comment by funnyJack** [comment]
由于微信小程序在正式使用时，只能发送 HTTPS 请求，所以这里阿里云中监听也必须设置为 HTTPS 请求。
为了使用 HTTPS 请求，需要购买域名，备案域名，购买 SSL 证书，配置域名解析等操作。

现在已经可以使用购买的域名 `ykytools.top` 直接解析到 ALB 中去。

注意配置 HTTPS 监听的时候需要设置端口为 443。可以将 HTTP 和 HTTPS 都配置监听。
